### ISSUE TITLE
Thank you for providing such a great project . 

### ISSUE THREAD

**Issue by yuequnwang** [openmedlab/PathoDuet#8]
Thank you for providing such a great project . I want an encoder similar to plip, which can generate 1*512 features for one H&E image.   
However, when I execute these two lines of code, the shape of the output features is  [4, 198, 768], which is different from the image embedding I expected.
So I want to know, can this project be used to extract embedding features?
**code ：** 
random_image = torch.randn(4,3,224,224)
output=model(a)

**Comment by hsymm** [comment]
You can replace the model.head with nn.Identity() to acquire raw features (a little change in the 'Get Started' code). The shape of output should be [B, 768]. However, if the shape is [B, 198, 768], you can manually do an average over the latter 196 features (i.e., output[:, 2: , :]). If you want features in the shape of 512, you could change the model.head with nn.Linear(768, 512) and finetune the newly-added layer.

**Comment by yuequnwang** [comment]
Thank you very much for your timely response! It resolved my questions!
